export const container = { height: "100%", display: "flex", flexDirection: "column" }
export const text_align_center = { textAlign: "center" }
export const headline_fredoka = { xs: "1rem", sm: "1.75rem", md: "2.5rem" }
export const headline_your_food = { xs: "1.5rem", sm: "2.5rem", md: "3.5rem" }
export const grid_container = { alignItems: "center", justifyContent: "space-evenly" }
export const sign_in_grid = { alignItems: "center", justifyContent: "space-evenly" }
export const sign_in_grid_size = { xs: 12, md: 6 }
export const sign_in_form = { height: { xs: "auto", md: "100%" } }
export const sign_in_image_grid = { display: { xs: "none", md: "block" } }
export const sign_in_image = { width:  "90%", height: "90%" }
